### ISSUE TITLE
command to build image in README doesn't work

### ISSUE THREAD

**Issue by outkaj** [cpurta/geth-devnet#2]
`docker build --build-arg DEV_CHAIN=false -f Dockerfile -t geth-devnet:<tag_name>` 
and `docker build --build-arg DEV_CHAIN=true -f Dockerfile -t geth-devnet:<tag_name>` both fail for me with `"docker build" requires exactly 1 argument.`

I needed to run `docker build . --build-arg DEV_CHAIN=true -f Dockerfile -t geth-devnet:<tag_name>` for the build to work. If this is the case for others, then perhaps the README should be updated? I am happy to open a PR.

**Comment by cpurta** [comment]
Thanks for filing an issue. I just updated the commands in the README to have to current directory as the build context which should be the project root. Running those updated commands worked for me.

**Comment by outkaj** [comment]
Thanks! Closing
